# Generated by Django 4.1.5 on 2023-01-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('techno', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
