# Generated by Django 4.1.5 on 2023-01-20 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_delete_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='eid',
            new_name='status',
        ),
    ]
