# Generated by Django 4.1.5 on 2023-01-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projects_description_alter_projects_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(max_length=200, null='True'),
        ),
    ]
